// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ddictrl.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DDICtrlResponse struct {
	Succeed              bool     `protobuf:"varint,1,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DDICtrlResponse) Reset()         { *m = DDICtrlResponse{} }
func (m *DDICtrlResponse) String() string { return proto.CompactTextString(m) }
func (*DDICtrlResponse) ProtoMessage()    {}
func (*DDICtrlResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddictrl_1d51842e1e1fe8d2, []int{0}
}
func (m *DDICtrlResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DDICtrlResponse.Unmarshal(m, b)
}
func (m *DDICtrlResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DDICtrlResponse.Marshal(b, m, deterministic)
}
func (dst *DDICtrlResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DDICtrlResponse.Merge(dst, src)
}
func (m *DDICtrlResponse) XXX_Size() int {
	return xxx_messageInfo_DDICtrlResponse.Size(m)
}
func (m *DDICtrlResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DDICtrlResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DDICtrlResponse proto.InternalMessageInfo

func (m *DDICtrlResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

type MasterUpRequest struct {
	MasterIp             string   `protobuf:"bytes,1,opt,name=master_ip,json=masterIp,proto3" json:"master_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterUpRequest) Reset()         { *m = MasterUpRequest{} }
func (m *MasterUpRequest) String() string { return proto.CompactTextString(m) }
func (*MasterUpRequest) ProtoMessage()    {}
func (*MasterUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddictrl_1d51842e1e1fe8d2, []int{1}
}
func (m *MasterUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterUpRequest.Unmarshal(m, b)
}
func (m *MasterUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterUpRequest.Marshal(b, m, deterministic)
}
func (dst *MasterUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterUpRequest.Merge(dst, src)
}
func (m *MasterUpRequest) XXX_Size() int {
	return xxx_messageInfo_MasterUpRequest.Size(m)
}
func (m *MasterUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterUpRequest proto.InternalMessageInfo

func (m *MasterUpRequest) GetMasterIp() string {
	if m != nil {
		return m.MasterIp
	}
	return ""
}

type MasterDownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MasterDownRequest) Reset()         { *m = MasterDownRequest{} }
func (m *MasterDownRequest) String() string { return proto.CompactTextString(m) }
func (*MasterDownRequest) ProtoMessage()    {}
func (*MasterDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ddictrl_1d51842e1e1fe8d2, []int{2}
}
func (m *MasterDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasterDownRequest.Unmarshal(m, b)
}
func (m *MasterDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasterDownRequest.Marshal(b, m, deterministic)
}
func (dst *MasterDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasterDownRequest.Merge(dst, src)
}
func (m *MasterDownRequest) XXX_Size() int {
	return xxx_messageInfo_MasterDownRequest.Size(m)
}
func (m *MasterDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MasterDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MasterDownRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DDICtrlResponse)(nil), "proto.DDICtrlResponse")
	proto.RegisterType((*MasterUpRequest)(nil), "proto.MasterUpRequest")
	proto.RegisterType((*MasterDownRequest)(nil), "proto.MasterDownRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DDICtrlManagerClient is the client API for DDICtrlManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DDICtrlManagerClient interface {
	MasterUp(ctx context.Context, in *MasterUpRequest, opts ...grpc.CallOption) (*DDICtrlResponse, error)
	MasterDown(ctx context.Context, in *MasterDownRequest, opts ...grpc.CallOption) (*DDICtrlResponse, error)
}

type dDICtrlManagerClient struct {
	cc *grpc.ClientConn
}

func NewDDICtrlManagerClient(cc *grpc.ClientConn) DDICtrlManagerClient {
	return &dDICtrlManagerClient{cc}
}

func (c *dDICtrlManagerClient) MasterUp(ctx context.Context, in *MasterUpRequest, opts ...grpc.CallOption) (*DDICtrlResponse, error) {
	out := new(DDICtrlResponse)
	err := c.cc.Invoke(ctx, "/proto.DDICtrlManager/MasterUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dDICtrlManagerClient) MasterDown(ctx context.Context, in *MasterDownRequest, opts ...grpc.CallOption) (*DDICtrlResponse, error) {
	out := new(DDICtrlResponse)
	err := c.cc.Invoke(ctx, "/proto.DDICtrlManager/MasterDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DDICtrlManagerServer is the server API for DDICtrlManager service.
type DDICtrlManagerServer interface {
	MasterUp(context.Context, *MasterUpRequest) (*DDICtrlResponse, error)
	MasterDown(context.Context, *MasterDownRequest) (*DDICtrlResponse, error)
}

func RegisterDDICtrlManagerServer(s *grpc.Server, srv DDICtrlManagerServer) {
	s.RegisterService(&_DDICtrlManager_serviceDesc, srv)
}

func _DDICtrlManager_MasterUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDICtrlManagerServer).MasterUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDICtrlManager/MasterUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDICtrlManagerServer).MasterUp(ctx, req.(*MasterUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DDICtrlManager_MasterDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MasterDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DDICtrlManagerServer).MasterDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DDICtrlManager/MasterDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DDICtrlManagerServer).MasterDown(ctx, req.(*MasterDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DDICtrlManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DDICtrlManager",
	HandlerType: (*DDICtrlManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MasterUp",
			Handler:    _DDICtrlManager_MasterUp_Handler,
		},
		{
			MethodName: "MasterDown",
			Handler:    _DDICtrlManager_MasterDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ddictrl.proto",
}

func init() { proto.RegisterFile("ddictrl.proto", fileDescriptor_ddictrl_1d51842e1e1fe8d2) }

var fileDescriptor_ddictrl_1d51842e1e1fe8d2 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x49, 0xc9, 0x4c,
	0x2e, 0x29, 0xca, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0xda, 0x5c,
	0xfc, 0x2e, 0x2e, 0x9e, 0xce, 0x25, 0x45, 0x39, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9,
	0x42, 0x12, 0x5c, 0xec, 0xc5, 0xa5, 0xc9, 0xc9, 0xa9, 0xa9, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x1c, 0x41, 0x30, 0xae, 0x92, 0x1e, 0x17, 0xbf, 0x6f, 0x62, 0x71, 0x49, 0x6a, 0x51, 0x68, 0x41,
	0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x34, 0x17, 0x67, 0x2e, 0x58, 0x28, 0x3e, 0xb3,
	0x00, 0xac, 0x9c, 0x33, 0x88, 0x03, 0x22, 0xe0, 0x59, 0xa0, 0x24, 0xcc, 0x25, 0x08, 0x51, 0xef,
	0x92, 0x5f, 0x9e, 0x07, 0xd5, 0x61, 0x34, 0x81, 0x91, 0x8b, 0x0f, 0x6a, 0xa5, 0x6f, 0x62, 0x5e,
	0x62, 0x7a, 0x6a, 0x91, 0x90, 0x0d, 0x17, 0x07, 0xcc, 0x5c, 0x21, 0x31, 0x88, 0xfb, 0xf4, 0xd0,
	0x2c, 0x92, 0x82, 0x89, 0xa3, 0xb9, 0x56, 0x89, 0x41, 0xc8, 0x81, 0x8b, 0x0b, 0x61, 0x8b, 0x90,
	0x04, 0x8a, 0x7e, 0x24, 0x8b, 0x71, 0x9b, 0x90, 0xc4, 0x06, 0x96, 0x30, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xed, 0x05, 0xe8, 0xf9, 0x23, 0x01, 0x00, 0x00,
}
